---
# tasks file for ansible-role-devfsrules

- name: Create devfsrules_file
  template:
    src: devfs.rules.j2
    dest: "{{ devfsrules_file }}"
  notify: Restart devfs

- name: Replace devfs_system_ruleset
  lineinfile:
    dest: /etc/rc.conf
    regexp: "^devfs_system_ruleset="
    line: "devfs_system_ruleset=\"{{ devfsrules_devfs_system_ruleset | join(' ') }}\""
  when: devfsrules_devfs_system_ruleset | length > 0
  notify: Restart devfs

- name: Remove devfs_system_ruleset when devfsrules_devfs_system_ruleset is empty
  lineinfile:
    dest: /etc/rc.conf
    regexp: "^devfs_system_ruleset=.*"
    state: absent
  when: devfsrules_devfs_system_ruleset | length == 0
  notify: Restart devfs
